# TCL File Generated by Component Editor 21.1
# Wed May 14 10:19:11 EDT 2025
# DO NOT MODIFY


# 
# admm_solver "ADMM_Solver" v1.0
# Alex Du 2025.05.14.10:19:11
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module admm_solver
# 
set_module_property DESCRIPTION ""
set_module_property NAME admm_solver
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Alex Du"
set_module_property DISPLAY_NAME ADMM_Solver
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL admm_solver
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file admm_solver.sv SYSTEM_VERILOG PATH ../admm_solver.sv TOP_LEVEL_FILE
add_fileset_file dual_update.sv SYSTEM_VERILOG PATH ../dual_update.sv
add_fileset_file memory_interface.sv SYSTEM_VERILOG PATH ../memory_interface.sv
add_fileset_file primal_update.sv SYSTEM_VERILOG PATH ../primal_update.sv
add_fileset_file RAM.v VERILOG PATH ../RAM.v
add_fileset_file residual_calculator.sv SYSTEM_VERILOG PATH ../residual_calculator.sv
add_fileset_file slack_update.sv SYSTEM_VERILOG PATH ../slack_update.sv


# 
# parameters
# 
add_parameter STATE_DIM INTEGER 12
set_parameter_property STATE_DIM DEFAULT_VALUE 12
set_parameter_property STATE_DIM DISPLAY_NAME STATE_DIM
set_parameter_property STATE_DIM TYPE INTEGER
set_parameter_property STATE_DIM UNITS None
set_parameter_property STATE_DIM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property STATE_DIM HDL_PARAMETER true
add_parameter INPUT_DIM INTEGER 4
set_parameter_property INPUT_DIM DEFAULT_VALUE 4
set_parameter_property INPUT_DIM DISPLAY_NAME INPUT_DIM
set_parameter_property INPUT_DIM TYPE INTEGER
set_parameter_property INPUT_DIM UNITS None
set_parameter_property INPUT_DIM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INPUT_DIM HDL_PARAMETER true
add_parameter HORIZON INTEGER 30
set_parameter_property HORIZON DEFAULT_VALUE 30
set_parameter_property HORIZON DISPLAY_NAME HORIZON
set_parameter_property HORIZON TYPE INTEGER
set_parameter_property HORIZON UNITS None
set_parameter_property HORIZON ALLOWED_RANGES -2147483648:2147483647
set_parameter_property HORIZON HDL_PARAMETER true
add_parameter MAX_ITER INTEGER 100
set_parameter_property MAX_ITER DEFAULT_VALUE 100
set_parameter_property MAX_ITER DISPLAY_NAME MAX_ITER
set_parameter_property MAX_ITER TYPE INTEGER
set_parameter_property MAX_ITER UNITS None
set_parameter_property MAX_ITER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAX_ITER HDL_PARAMETER true
add_parameter EXT_DATA_WIDTH INTEGER 32
set_parameter_property EXT_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property EXT_DATA_WIDTH DISPLAY_NAME EXT_DATA_WIDTH
set_parameter_property EXT_DATA_WIDTH TYPE INTEGER
set_parameter_property EXT_DATA_WIDTH UNITS None
set_parameter_property EXT_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property EXT_DATA_WIDTH HDL_PARAMETER true
add_parameter DATA_WIDTH INTEGER 16
set_parameter_property DATA_WIDTH DEFAULT_VALUE 16
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter FRAC_BITS INTEGER 8
set_parameter_property FRAC_BITS DEFAULT_VALUE 8
set_parameter_property FRAC_BITS DISPLAY_NAME FRAC_BITS
set_parameter_property FRAC_BITS TYPE INTEGER
set_parameter_property FRAC_BITS UNITS None
set_parameter_property FRAC_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FRAC_BITS HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 16
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 16
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter MEM_ADDR_WIDTH INTEGER 9
set_parameter_property MEM_ADDR_WIDTH DEFAULT_VALUE 9
set_parameter_property MEM_ADDR_WIDTH DISPLAY_NAME MEM_ADDR_WIDTH
set_parameter_property MEM_ADDR_WIDTH TYPE INTEGER
set_parameter_property MEM_ADDR_WIDTH UNITS None
set_parameter_property MEM_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MEM_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point admm_solver_0
# 
add_interface admm_solver_0 avalon end
set_interface_property admm_solver_0 addressUnits WORDS
set_interface_property admm_solver_0 associatedClock clock
set_interface_property admm_solver_0 associatedReset rst
set_interface_property admm_solver_0 bitsPerSymbol 32
set_interface_property admm_solver_0 burstOnBurstBoundariesOnly false
set_interface_property admm_solver_0 burstcountUnits WORDS
set_interface_property admm_solver_0 explicitAddressSpan 0
set_interface_property admm_solver_0 holdTime 0
set_interface_property admm_solver_0 linewrapBursts false
set_interface_property admm_solver_0 maximumPendingReadTransactions 0
set_interface_property admm_solver_0 maximumPendingWriteTransactions 0
set_interface_property admm_solver_0 readLatency 0
set_interface_property admm_solver_0 readWaitTime 1
set_interface_property admm_solver_0 setupTime 0
set_interface_property admm_solver_0 timingUnits Cycles
set_interface_property admm_solver_0 writeWaitTime 0
set_interface_property admm_solver_0 ENABLED true
set_interface_property admm_solver_0 EXPORT_OF ""
set_interface_property admm_solver_0 PORT_NAME_MAP ""
set_interface_property admm_solver_0 CMSIS_SVD_VARIABLES ""
set_interface_property admm_solver_0 SVD_ADDRESS_GROUP ""

add_interface_port admm_solver_0 writedata writedata Input "((EXT_DATA_WIDTH-1)) - (0) + 1"
add_interface_port admm_solver_0 read read Input 1
add_interface_port admm_solver_0 write write Input 1
add_interface_port admm_solver_0 addr address Input "((ADDR_WIDTH-1)) - (0) + 1"
add_interface_port admm_solver_0 chipselect chipselect Input 1
add_interface_port admm_solver_0 readdata readdata Output "((EXT_DATA_WIDTH-1)) - (0) + 1"
set_interface_assignment admm_solver_0 embeddedsw.configuration.isFlash 0
set_interface_assignment admm_solver_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment admm_solver_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment admm_solver_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clock
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst reset Input 1

